mutation PasswordSave($id: String!, $title: String, $username: String, $icon: String, $fields: [FieldInput]) {
  editPassword(_id: $id, title: $title, username: $username, icon: $icon, fields: $fields) {
    _id
    title
    username
    icon
    fields {
      title
      value
    }
  }
}
