mutation PasswordSave($id: String!, $title: String, $username: String, $icon: String, $fields: [FieldInput], $notes: RawType) {
  editPassword(_id: $id, title: $title, username: $username, icon: $icon, fields: $fields, notes: $notes) {
    _id
    title
    username
    icon
    notes
    fields {
      title
      value
    }
  }
}
